//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _17._02._2020_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Book_Name { get; set; }
        public int Author_Id { get; set; }
        public int Language_id { get; set; }
        public int Pages_count { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Language Language { get; set; }
    }
}
