//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20._02._2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specializations
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int StudentsId { get; set; }
        public int SubjectsId { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
