//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20._02._2020
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnivesriryCtx2Container : DbContext
    {
        public UnivesriryCtx2Container()
            : base("name=UnivesriryCtx2Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Specializations> Specializations { get; set; }
        public virtual DbSet<Students> StudentsSet { get; set; }
        public virtual DbSet<Subjects> SubjectsSet { get; set; }
    }
}
