<?xml version="1.0" encoding="utf-8"?><Database Name="LIBRARY" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-D4LSJMD\SQLEXPRESS;Initial Catalog=LIBRARY;Integrated Security=True" SettingsObjectName="_22._02._2020.Properties.Settings" SettingsPropertyName="LIBRARYConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Authors" Member="Authors">
    <Type Name="Authors">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Author_Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Author_Surname" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Authors_Books" Member="Books" ThisKey="Id" OtherKey="Author_Id" Type="Books" />
    </Type>
  </Table>
  <Table Name="dbo.Books" Member="Books">
    <Type Name="Books">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Book_Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Author_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Language_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pages_count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Authors_Books" Member="Authors" ThisKey="Author_Id" OtherKey="Id" Type="Authors" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Languages_Books" Member="Languages" ThisKey="Language_id" OtherKey="Id" Type="Languages" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Countries" Member="Countries">
    <Type Name="Countries">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Association Name="Countries_Languages" Member="Languages" ThisKey="Id" OtherKey="Country_id" Type="Languages" />
    </Type>
  </Table>
  <Table Name="dbo.Languages" Member="Languages">
    <Type Name="Languages">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Language_Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Country_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Languages_Books" Member="Books" ThisKey="Id" OtherKey="Language_id" Type="Books" />
      <Association Name="Countries_Languages" Member="Countries" ThisKey="Country_id" OtherKey="Id" Type="Countries" IsForeignKey="true" />
    </Type>
  </Table>
</Database>